django/lecture3/hello/urls.py
from unicodedata import name
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
]

django/lecture3/lecture3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include('hello.urls')),
    path("newyear/", include('newyear.urls')),
    path("tasks/", include('tasks.urls')),
]


# start from min 25

django/lecture3/newyear/urls.py
from unicodedata import name
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
]

django/lecture3/tasks/urls.py
from unicodedata import name
from django.urls import path

from . import views

app_name = "tasks"

urlpatterns = [
    path('', views.index, name="index"),
    path('add/', views.add, name="add")
]

django/lecture3/hello/models.py
from django.db import models

# Create your models here.

django/lecture3/newyear/models.py
from django.db import models

# Create your models here.

django/lecture3/tasks/models.py
from django.db import models

# Create your models here.

django/lecture3/hello/views.py
from django.http import HttpResponse
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize(),
    })

django/lecture3/newyear/views.py
import datetime

from django.shortcuts import render
# Create your views here.

def index(request):
    now = datetime.datetime.now()

    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1,
    })

django/lecture3/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse



class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")

def index(request):
    if "tasks" not in request.session:
        request.session['tasks'] = []
    return render(
        request,
        "tasks/index.html",
        {
            "tasks": request.session["tasks"]
        }
    )

def add(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data['task']
            request.session['tasks'] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(
                request,
                "tasks/add.html",
                {
                    "form": form,
                }
            )

    return render(
        request,
        "tasks/add.html",
        {
            'form': NewTaskForm()
        }
    )

# start from 1:23

django/lecture3/hello/templates/hello/greet.html
<!DOCTYPE html>
<html>
    <head>
        <title>Greet Page</title>
    </head>
    <body>
        <h1>Hello, {{ name }}</h1>
    </body>
</html>

django/lecture3/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hello app</title>
</head>
<body>
    <h1>Hello, World!</h1>
</body>
</html>

django/lecture3/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <title>Is it new year ?</title>
        <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
    </head>
    <body>
        {% if newyear %}
            <h1>Yes</h1>
        {% else %}
            <h1>No</h1>
        {% endif %}
    </body>
</html>

django/lecture3/tasks/templates/tasks/add.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <h1>Add task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        {{form}}
        <input type="submit">
    </form>

    <a href="{% url 'tasks:index' %}">Tasks View</a>
{% endblock %}

django/lecture3/tasks/templates/tasks/index.html
{% extends 'tasks/layout.html' %}

{% block body %}
    <h1>Tasks</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No task.</li>
        {% endfor %}
    </ul>

    <a href="{% url 'tasks:add' %}">Add new tasks</a>
{% endblock %}

django/lecture3/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>Tasks</title>
    </head>
    <body>
        {% block body %}
        {% endblock %}
    </body>
</html>